package com.worksy.ui.employer;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import com.google.firebase.auth.FirebaseAuth;
import com.worksy.data.model.EmployeeRating;
import com.worksy.data.repository.EmployeeRatingRepository;
import com.worksy.databinding.FragmentRateJobSeekerBinding;

public class RateEmployeeFragment extends Fragment {
    private FragmentRateJobSeekerBinding binding;
    private EmployeeRatingRepository ratingRepository;
    private String employeeId;
    private String jobId;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ratingRepository = new EmployeeRatingRepository();
        
        // Get employeeId and jobId from arguments
        if (getArguments() != null) {
            employeeId = getArguments().getString("employeeId");
            jobId = getArguments().getString("jobId");
        }
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        binding = FragmentRateJobSeekerBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        binding.submitRatingButton.setOnClickListener(v -> submitRating());
    }

    private void submitRating() {
        if (employeeId == null || jobId == null) {
            Toast.makeText(requireContext(), "Missing required information", Toast.LENGTH_SHORT).show();
            return;
        }

        String employerId = FirebaseAuth.getInstance().getCurrentUser().getUid();
        float skillsKnowledge = binding.ratingSkillsKnowledge.getRating();
        float qualityOfWork = binding.ratingQualityOfWork.getRating();
        float communicationSkills = binding.ratingCommunicationSkills.getRating();
        float initiativeProactiveness = binding.ratingInitiativeProactiveness.getRating();
        float teamworkCollaboration = binding.ratingTeamworkCollaboration.getRating();

        // Validate ratings
        if (skillsKnowledge == 0 || qualityOfWork == 0 || communicationSkills == 0 || 
            initiativeProactiveness == 0 || teamworkCollaboration == 0) {
            Toast.makeText(requireContext(), "Please provide ratings for all categories", Toast.LENGTH_SHORT).show();
            return;
        }

        EmployeeRating rating = new EmployeeRating(
            null, // ID will be generated by Firestore
            employerId,
            employeeId,
            skillsKnowledge,
            qualityOfWork,
            communicationSkills,
            initiativeProactiveness,
            teamworkCollaboration,
            jobId
        );

        ratingRepository.createRating(rating)
            .addOnSuccessListener(aVoid -> {
                Toast.makeText(requireContext(), "Rating submitted successfully", Toast.LENGTH_SHORT).show();
                requireActivity().onBackPressed(); // Go back to previous screen
            })
            .addOnFailureListener(e -> {
                Toast.makeText(requireContext(), "Failed to submit rating: " + e.getMessage(), Toast.LENGTH_SHORT).show();
            });
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}
